all:
	@g++ -Wall main.cpp -o SRD
	@./SRD short_test.txt compressed.txt decompressed.txt
# @echo "\n----------ORIGINAL DATA----------\n"
# @cat test_data.txt
# @echo "\n---------COMPRESSED DATA---------\n"
# @cat output.txt
# @echo "\n--------DECOMPRESSED DATA--------\n"
#@rm out.txt
	@rm SRD
